camera_matrix:
  cols: 3
  data:
  - 900.0
  - 0.0
  - 640.0
  - 0.0
  - 900.0
  - 480.0
  - 0.0
  - 0.0
  - 1.0
  rows: 3
camera_name: usb_cam
distortion_coefficients:
  cols: 5
  data:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  rows: 1
distortion_model: plumb_bob
image_height: 960
image_width: 1280
projection_matrix:
  cols: 4
  data:
  - 900.0
  - 0.0
  - 640.0
  - 0.0
  - 0.0
  - 900.0
  - 480.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  rows: 3
rectification_matrix:
  cols: 3
  data:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 3
