camera_matrix:
  cols: 3
  data:
  - 2552.386292759887
  - 0.0
  - 2347.697864142568
  - 0.0
  - 2488.6710752960707
  - 906.0893844804999
  - 0.0
  - 0.0
  - 1.0
  rows: 3
camera_name: usb_cam
distortion_coefficients:
  cols: 5
  data:
  - 0.05758600956737407
  - 0.1768777169471388
  - -0.011227692176072687
  - 0.05327824854410622
  - 0.038592917524052486
  rows: 1
distortion_model: plumb_bob
image_height: 2160
image_width: 3840
projection_matrix:
  cols: 4
  data:
  - 2552.386292759887
  - 0.0
  - 2347.697864142568
  - 0.0
  - 0.0
  - 2488.6710752960707
  - 906.0893844804999
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  rows: 3
rectification_matrix:
  cols: 3
  data:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  rows: 3
